import sys

path = sys.argv[1] + r"/platform/fast3d/gfx_opengl.c"

with open(path, "r", encoding="utf-8") as f:
    src = f.read()

old = (
    "static void dkr_vita_rewrite_glsl_to_legacy(char *buf, size_t *len, int is_fragment) {\n"
    "    static char tmp[18432];\n"
    "    size_t out_len = 0;\n"
    "    size_t i = 0;\n"
    "    size_t total = *len;\n"
    "    while (i < total) {\n"
    "        size_t line_start = i;\n"
    "        while (i < total && buf[i] != '\\n') {\n"
    "            i++;\n"
    "        }\n"
    "        size_t raw_line_len = i - line_start;\n"
    "        int had_newline = (i < total);\n"
    "        if (had_newline) {\n"
    "            i++;\n"
    "        }\n"
    "\n"
    "        char rewritten[512];\n"
    "        size_t rewritten_len = dkr_vita_rewrite_line_fragcolor(\n"
    "            rewritten, sizeof(rewritten), buf + line_start, raw_line_len);\n"
    "\n"
    "        if (rewritten_len == strlen(\"out vec4 gl_FragColor;\") &&\n"
    "            memcmp(rewritten, \"out vec4 gl_FragColor;\", rewritten_len) == 0) {\n"
    "            /* Drop: redeclaring the gl_FragColor builtin is illegal once\n"
    "             * it's the rename target above. */\n"
    "            continue;\n"
    "        }\n"
    "\n"
    "        const char *new_prefix = NULL;\n"
    "        size_t old_prefix_len = 0;\n"
    "        if (rewritten_len >= 3 && memcmp(rewritten, \"in \", 3) == 0) {\n"
    "            new_prefix = is_fragment ? \"varying \" : \"attribute \";\n"
    "            old_prefix_len = 3;\n"
    "        } else if (rewritten_len >= 4 && memcmp(rewritten, \"out \", 4) == 0) {\n"
    "            new_prefix = \"varying \";\n"
    "            old_prefix_len = 4;\n"
    "        }\n"
    "\n"
    "        if (new_prefix != NULL) {\n"
    "            size_t new_prefix_len = strlen(new_prefix);\n"
    "            memcpy(tmp + out_len, new_prefix, new_prefix_len);\n"
    "            out_len += new_prefix_len;\n"
    "            size_t rest_len = rewritten_len - old_prefix_len;\n"
    "            memcpy(tmp + out_len, rewritten + old_prefix_len, rest_len);\n"
    "            out_len += rest_len;\n"
    "        } else {\n"
    "            memcpy(tmp + out_len, rewritten, rewritten_len);\n"
    "            out_len += rewritten_len;\n"
    "        }\n"
    "        if (had_newline) {\n"
    "            tmp[out_len++] = '\\n';\n"
    "        }\n"
    "    }\n"
    "    memcpy(buf, tmp, out_len);\n"
    "    *len = out_len;\n"
    "}\n"
)
assert src.count(old) == 1, "count=%d" % src.count(old)

new = (
    "static void dkr_vita_rewrite_glsl_to_legacy(char *buf, size_t *len, int is_fragment) {\n"
    "    static char tmp[18432];\n"
    "    size_t out_len = 0;\n"
    "    size_t i = 0;\n"
    "    size_t total = *len;\n"
    "    while (i < total) {\n"
    "        size_t line_start = i;\n"
    "        while (i < total && buf[i] != '\\n') {\n"
    "            i++;\n"
    "        }\n"
    "        size_t raw_line_len = i - line_start;\n"
    "        int had_newline = (i < total);\n"
    "        if (had_newline) {\n"
    "            i++;\n"
    "        }\n"
    "\n"
    "        /* Step 1: textureLod(tex, uv, 0.0) -> drop the explicit-LOD\n"
    "         * argument. Every textureLod() call this generator emits samples\n"
    "         * at LOD 0 and ends its statement with the literal \", 0.0);\"\n"
    "         * suffix (checked against the actual generator: true in every\n"
    "         * call site as of this writing), so a plain suffix strip is\n"
    "         * enough -- no expression parsing needed. */\n"
    "        char stage1[768];\n"
    "        size_t stage1_len;\n"
    "        {\n"
    "            static const char kLodSuffix[] = \", 0.0);\";\n"
    "            size_t suffix_len = sizeof(kLodSuffix) - 1;\n"
    "            if (raw_line_len >= suffix_len &&\n"
    "                memcmp(buf + line_start + raw_line_len - suffix_len, kLodSuffix,\n"
    "                       suffix_len) == 0) {\n"
    "                size_t keep_len = raw_line_len - suffix_len;\n"
    "                memcpy(stage1, buf + line_start, keep_len);\n"
    "                stage1_len = keep_len;\n"
    "                stage1[stage1_len++] = ')';\n"
    "                stage1[stage1_len++] = ';';\n"
    "            } else {\n"
    "                memcpy(stage1, buf + line_start, raw_line_len);\n"
    "                stage1_len = raw_line_len;\n"
    "            }\n"
    "        }\n"
    "\n"
    "        /* Step 2: texture(/textureLod( -> texture2D(. vitaGL's runtime\n"
    "         * translator's texture-sampling handling only recognizes the\n"
    "         * legacy GLSL ES 1.00 call name; the unified ES3 texture()\n"
    "         * overload passes straight through as unrecognized Cg and\n"
    "         * hard-aborts the closed-source compiler, same failure mode as\n"
    "         * the in/out/fragColor issue this function was first written\n"
    "         * for. */\n"
    "        char stage2[768];\n"
    "        size_t stage2_len = 0;\n"
    "        {\n"
    "            size_t j = 0;\n"
    "            while (j < stage1_len) {\n"
    "                if (j + 11 <= stage1_len && memcmp(stage1 + j, \"textureLod(\", 11) == 0) {\n"
    "                    memcpy(stage2 + stage2_len, \"texture2D(\", 10);\n"
    "                    stage2_len += 10;\n"
    "                    j += 11;\n"
    "                    continue;\n"
    "                }\n"
    "                if (j + 8 <= stage1_len && memcmp(stage1 + j, \"texture(\", 8) == 0) {\n"
    "                    memcpy(stage2 + stage2_len, \"texture2D(\", 10);\n"
    "                    stage2_len += 10;\n"
    "                    j += 8;\n"
    "                    continue;\n"
    "                }\n"
    "                stage2[stage2_len++] = stage1[j++];\n"
    "            }\n"
    "        }\n"
    "\n"
    "        char rewritten[768];\n"
    "        size_t rewritten_len = dkr_vita_rewrite_line_fragcolor(\n"
    "            rewritten, sizeof(rewritten), stage2, stage2_len);\n"
    "\n"
    "        if (rewritten_len == strlen(\"out vec4 gl_FragColor;\") &&\n"
    "            memcmp(rewritten, \"out vec4 gl_FragColor;\", rewritten_len) == 0) {\n"
    "            /* Drop: redeclaring the gl_FragColor builtin is illegal once\n"
    "             * it's the rename target above. */\n"
    "            continue;\n"
    "        }\n"
    "\n"
    "        const char *new_prefix = NULL;\n"
    "        size_t old_prefix_len = 0;\n"
    "        if (rewritten_len >= 3 && memcmp(rewritten, \"in \", 3) == 0) {\n"
    "            new_prefix = is_fragment ? \"varying \" : \"attribute \";\n"
    "            old_prefix_len = 3;\n"
    "        } else if (rewritten_len >= 4 && memcmp(rewritten, \"out \", 4) == 0) {\n"
    "            new_prefix = \"varying \";\n"
    "            old_prefix_len = 4;\n"
    "        }\n"
    "\n"
    "        if (new_prefix != NULL) {\n"
    "            size_t new_prefix_len = strlen(new_prefix);\n"
    "            memcpy(tmp + out_len, new_prefix, new_prefix_len);\n"
    "            out_len += new_prefix_len;\n"
    "            size_t rest_len = rewritten_len - old_prefix_len;\n"
    "            memcpy(tmp + out_len, rewritten + old_prefix_len, rest_len);\n"
    "            out_len += rest_len;\n"
    "        } else {\n"
    "            memcpy(tmp + out_len, rewritten, rewritten_len);\n"
    "            out_len += rewritten_len;\n"
    "        }\n"
    "        if (had_newline) {\n"
    "            tmp[out_len++] = '\\n';\n"
    "        }\n"
    "    }\n"
    "    memcpy(buf, tmp, out_len);\n"
    "    *len = out_len;\n"
    "}\n"
)
src = src.replace(old, new, 1)

with open(path, "wb") as f:
    f.write(src.encode("utf-8"))

print("patched", path)
