import sys

path = sys.argv[1] + r"/platform/fast3d/gfx_opengl.c"

with open(path, "r", encoding="utf-8") as f:
    src = f.read()

# 1) Insert the rewrite helpers right before
#    gfx_opengl_create_and_load_new_shader (which already carries a Vita-only
#    extern decl for mdkr_vita_boot_log immediately above it, from an earlier
#    patch -- anchor on the function signature itself so this works either
#    way).
anchor_fn = (
    "static struct ShaderProgram *gfx_opengl_create_and_load_new_shader"
    "(uint64_t shader_id0, uint32_t shader_id1) {\n"
)
assert src.count(anchor_fn) == 1, "fn anchor count=%d" % src.count(anchor_fn)

helpers = (
    "#if defined(__vita__)\n"
    "static int dkr_vita_is_ident_char(char c) {\n"
    "    return c == '_' ||\n"
    "           (c >= '0' && c <= '9') ||\n"
    "           (c >= 'a' && c <= 'z') ||\n"
    "           (c >= 'A' && c <= 'Z');\n"
    "}\n"
    "\n"
    "/* Copies `line` into `dst`, rewriting every whole-word occurrence of\n"
    " * \"fragColor\" into \"gl_FragColor\". Returns the number of bytes written\n"
    " * (never NUL-terminated; caller tracks length explicitly). */\n"
    "static size_t dkr_vita_rewrite_line_fragcolor(char *dst, size_t dst_cap,\n"
    "                                               const char *line, size_t line_len) {\n"
    "    size_t out = 0;\n"
    "    size_t i = 0;\n"
    "    while (i < line_len) {\n"
    "        int is_word_start = (i == 0) || !dkr_vita_is_ident_char(line[i - 1]);\n"
    "        if (is_word_start && (line_len - i) >= 9 &&\n"
    "            strncmp(line + i, \"fragColor\", 9) == 0 &&\n"
    "            ((i + 9 >= line_len) || !dkr_vita_is_ident_char(line[i + 9]))) {\n"
    "            if (out + 12 > dst_cap) {\n"
    "                break;\n"
    "            }\n"
    "            memcpy(dst + out, \"gl_FragColor\", 12);\n"
    "            out += 12;\n"
    "            i += 9;\n"
    "            continue;\n"
    "        }\n"
    "        if (out + 1 > dst_cap) {\n"
    "            break;\n"
    "        }\n"
    "        dst[out++] = line[i++];\n"
    "    }\n"
    "    return out;\n"
    "}\n"
    "\n"
    "/* vitaGL's runtime GLSL->Cg translator only understands the legacy\n"
    " * WebGL/GLSL-ES-1.00 dialect: `attribute`/`varying` storage qualifiers\n"
    " * and the builtin `gl_FragColor` output (its glsl_translator_hdr.h\n"
    " * hardcodes exactly those semantic bindings; `#version`/`precision`\n"
    " * lines are safely comment-stripped, but there is no handling anywhere\n"
    " * in the translator for ES3 top-level `in`/`out` variable qualifiers or\n"
    " * a user-declared fragment output variable). This generator emits ES3-\n"
    " * style GLSL (`#version 320 es`, `in`/`out`, `out vec4 fragColor;`) for\n"
    " * the MGB64_PORTMASTER_GLES platforms it targets elsewhere; fed straight\n"
    " * through on Vita, those unrecognized qualifiers and the never-bound\n"
    " * `fragColor` output reach the closed-source vitaShaRK/Cg compiler as\n"
    " * malformed Cg, which hard-aborts() instead of failing gracefully --\n"
    " * the exact very-first-real-shader-compile crash this file's other\n"
    " * Vita-only diagnostics were added to chase. Rewrite the fully-built\n"
    " * source into the legacy dialect in place, line by line, before it is\n"
    " * ever handed to glCompileShader. */\n"
    "static void dkr_vita_rewrite_glsl_to_legacy(char *buf, size_t *len, int is_fragment) {\n"
    "    static char tmp[18432];\n"
    "    size_t out_len = 0;\n"
    "    size_t i = 0;\n"
    "    size_t total = *len;\n"
    "    while (i < total) {\n"
    "        size_t line_start = i;\n"
    "        while (i < total && buf[i] != '\\n') {\n"
    "            i++;\n"
    "        }\n"
    "        size_t raw_line_len = i - line_start;\n"
    "        int had_newline = (i < total);\n"
    "        if (had_newline) {\n"
    "            i++;\n"
    "        }\n"
    "\n"
    "        char rewritten[512];\n"
    "        size_t rewritten_len = dkr_vita_rewrite_line_fragcolor(\n"
    "            rewritten, sizeof(rewritten), buf + line_start, raw_line_len);\n"
    "\n"
    "        if (rewritten_len == strlen(\"out vec4 gl_FragColor;\") &&\n"
    "            memcmp(rewritten, \"out vec4 gl_FragColor;\", rewritten_len) == 0) {\n"
    "            /* Drop: redeclaring the gl_FragColor builtin is illegal once\n"
    "             * it's the rename target above. */\n"
    "            continue;\n"
    "        }\n"
    "\n"
    "        const char *new_prefix = NULL;\n"
    "        size_t old_prefix_len = 0;\n"
    "        if (rewritten_len >= 3 && memcmp(rewritten, \"in \", 3) == 0) {\n"
    "            new_prefix = is_fragment ? \"varying \" : \"attribute \";\n"
    "            old_prefix_len = 3;\n"
    "        } else if (rewritten_len >= 4 && memcmp(rewritten, \"out \", 4) == 0) {\n"
    "            new_prefix = \"varying \";\n"
    "            old_prefix_len = 4;\n"
    "        }\n"
    "\n"
    "        if (new_prefix != NULL) {\n"
    "            size_t new_prefix_len = strlen(new_prefix);\n"
    "            memcpy(tmp + out_len, new_prefix, new_prefix_len);\n"
    "            out_len += new_prefix_len;\n"
    "            size_t rest_len = rewritten_len - old_prefix_len;\n"
    "            memcpy(tmp + out_len, rewritten + old_prefix_len, rest_len);\n"
    "            out_len += rest_len;\n"
    "        } else {\n"
    "            memcpy(tmp + out_len, rewritten, rewritten_len);\n"
    "            out_len += rewritten_len;\n"
    "        }\n"
    "        if (had_newline) {\n"
    "            tmp[out_len++] = '\\n';\n"
    "        }\n"
    "    }\n"
    "    memcpy(buf, tmp, out_len);\n"
    "    *len = out_len;\n"
    "}\n"
    "#endif\n"
    "\n"
)
src = src.replace(anchor_fn, helpers + anchor_fn, 1)

# 2) Call the rewrite right before the shaders are handed to glCompileShader,
#    and extend the existing Vita diagnostic log to also dump the rewritten
#    source so it can be sanity-checked against the boot log.
old_call_site = (
    "#if defined(__vita__)\n"
    "    {\n"
    "        static int s_shaderLogCount = 0;\n"
    "        if (s_shaderLogCount < 20) {\n"
    "            char lb[192];\n"
    "            snprintf(lb, sizeof(lb),\n"
    "                     \"shader: about to compile+link id0=0x%llx id1=0x%x tex=%d,%d fog=%d \"\n"
    "                     \"alpha=%d 2cyc=%d inputs=%d worldpos=%d vs_len=%u fs_len=%u\",\n"
    "                     (unsigned long long)shader_id0, (unsigned)shader_id1,\n"
    "                     cc_features.used_textures[0], cc_features.used_textures[1],\n"
    "                     cc_features.opt_fog, cc_features.opt_alpha, cc_features.opt_2cyc,\n"
    "                     cc_features.num_inputs, cc_features.opt_world_pos,\n"
    "                     (unsigned)vs_len, (unsigned)fs_len);\n"
    "            mdkr_vita_boot_log(lb);\n"
    "            s_shaderLogCount++;\n"
    "        }\n"
    "    }\n"
    "#endif\n"
    "    const GLchar *sources[2] = { vs_buf, fs_buf };\n"
)
assert src.count(old_call_site) == 1, "call site count=%d" % src.count(old_call_site)

new_call_site = (
    "#if defined(__vita__)\n"
    "    {\n"
    "        static int s_shaderLogCount = 0;\n"
    "        if (s_shaderLogCount < 20) {\n"
    "            char lb[192];\n"
    "            snprintf(lb, sizeof(lb),\n"
    "                     \"shader: about to compile+link id0=0x%llx id1=0x%x tex=%d,%d fog=%d \"\n"
    "                     \"alpha=%d 2cyc=%d inputs=%d worldpos=%d vs_len=%u fs_len=%u (pre-rewrite)\",\n"
    "                     (unsigned long long)shader_id0, (unsigned)shader_id1,\n"
    "                     cc_features.used_textures[0], cc_features.used_textures[1],\n"
    "                     cc_features.opt_fog, cc_features.opt_alpha, cc_features.opt_2cyc,\n"
    "                     cc_features.num_inputs, cc_features.opt_world_pos,\n"
    "                     (unsigned)vs_len, (unsigned)fs_len);\n"
    "            mdkr_vita_boot_log(lb);\n"
    "            s_shaderLogCount++;\n"
    "        }\n"
    "    }\n"
    "    dkr_vita_rewrite_glsl_to_legacy(vs_buf, &vs_len, 0);\n"
    "    dkr_vita_rewrite_glsl_to_legacy(fs_buf, &fs_len, 1);\n"
    "    {\n"
    "        static int s_shaderSrcLogCount = 0;\n"
    "        if (s_shaderSrcLogCount < 5) {\n"
    "            char lb[600];\n"
    "            snprintf(lb, sizeof(lb), \"shader: rewritten VS (len=%u):\\n%.*s\",\n"
    "                     (unsigned)vs_len, (int)(vs_len < 500 ? vs_len : 500), vs_buf);\n"
    "            mdkr_vita_boot_log(lb);\n"
    "            snprintf(lb, sizeof(lb), \"shader: rewritten FS (len=%u):\\n%.*s\",\n"
    "                     (unsigned)fs_len, (int)(fs_len < 500 ? fs_len : 500), fs_buf);\n"
    "            mdkr_vita_boot_log(lb);\n"
    "            s_shaderSrcLogCount++;\n"
    "        }\n"
    "    }\n"
    "#endif\n"
    "    const GLchar *sources[2] = { vs_buf, fs_buf };\n"
)
src = src.replace(old_call_site, new_call_site, 1)

with open(path, "wb") as f:
    f.write(src.encode("utf-8"))

print("patched", path)
