# Reproducible native Phone Party transport.
#
# libdatachannel is pinned to an exact reviewed commit and built media-free:
# Phone Party needs WSS signaling plus WebRTC DataChannels, never RTP/media.
# Mbed TLS is pinned to its current 3.6 LTS security release so release builds
# do not acquire a Homebrew/OpenSSL runtime dependency.

include(FetchContent)

set(MDKR_MBEDTLS_VERSION "3.6.7")
set(MDKR_MBEDTLS_SHA256
    "a7e8bcbec0e6f761b4af24f25677626b35f762f68eef79c08677a363212d11f6")
set(MDKR_LIBDATACHANNEL_VERSION "0.24.5")
set(MDKR_LIBDATACHANNEL_COMMIT
    "443f6934d9007eb7076ab7825ba330f355fcbead")
set(MDKR_MOZILLA_CA_DATE "2026-07-16")
set(MDKR_MOZILLA_CA_SHA256
    "3ff344e30b9b1ed2971044eabb438a08f2e2245ddb5f8ab1a3ad8b63ab4eaf91")

# Mbed TLS's ordinary source archive carries generated files and its framework
# submodule content; GitHub's autogenerated source archive explicitly does not.
set(MDKR_MBEDTLS_USER_CONFIG
    "${CMAKE_BINARY_DIR}/generated/party/mdkr_mbedtls_user_config.h")
file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/generated/party")
set(MDKR_MBEDTLS_USER_CONFIG_CONTENT
    "#ifndef MDKR_MBEDTLS_USER_CONFIG_H\n#define MDKR_MBEDTLS_USER_CONFIG_H\n#define MBEDTLS_SSL_DTLS_SRTP\n#endif\n")
set(MDKR_MBEDTLS_USER_CONFIG_CURRENT "")
if(EXISTS "${MDKR_MBEDTLS_USER_CONFIG}")
    file(READ "${MDKR_MBEDTLS_USER_CONFIG}" MDKR_MBEDTLS_USER_CONFIG_CURRENT)
endif()
if(NOT MDKR_MBEDTLS_USER_CONFIG_CURRENT STREQUAL
       MDKR_MBEDTLS_USER_CONFIG_CONTENT)
    file(WRITE "${MDKR_MBEDTLS_USER_CONFIG}"
        "${MDKR_MBEDTLS_USER_CONFIG_CONTENT}")
endif()
set(MBEDTLS_USER_CONFIG_FILE "${MDKR_MBEDTLS_USER_CONFIG}"
    CACHE FILEPATH "" FORCE)
set(ENABLE_PROGRAMS OFF CACHE BOOL "" FORCE)
set(ENABLE_TESTING OFF CACHE BOOL "" FORCE)
set(USE_SHARED_MBEDTLS_LIBRARY OFF CACHE BOOL "" FORCE)
set(USE_STATIC_MBEDTLS_LIBRARY ON CACHE BOOL "" FORCE)
# DOWNLOAD_EXTRACT_TIMESTAMP exists only in CMake >= 3.24; older CMake folds
# the unknown keyword into URL_HASH and fails configure (Ubuntu 22.04 ships
# 3.22). Older CMake keeps archive timestamps, which mbedtls tolerates.
set(MDKR_MBEDTLS_EXTRACT_ARGS "")
if(CMAKE_VERSION VERSION_GREATER_EQUAL 3.24)
    set(MDKR_MBEDTLS_EXTRACT_ARGS DOWNLOAD_EXTRACT_TIMESTAMP TRUE)
endif()
FetchContent_Declare(mdkr_mbedtls
    URL
      "https://github.com/Mbed-TLS/mbedtls/releases/download/mbedtls-${MDKR_MBEDTLS_VERSION}/mbedtls-${MDKR_MBEDTLS_VERSION}.tar.bz2"
    URL_HASH "SHA256=${MDKR_MBEDTLS_SHA256}"
    ${MDKR_MBEDTLS_EXTRACT_ARGS})
FetchContent_MakeAvailable(mdkr_mbedtls)
if(NOT TARGET MbedTLS::MbedTLS)
    # libdatachannel uses the package-style aggregate name while Mbed TLS's
    # add_subdirectory build exports component aliases.  Keep the aggregate an
    # imported facade: an ALIAS resolves to the local `mbedtls` target and then
    # makes libdatachannel's install export incorrectly claim ownership of it.
    add_library(MbedTLS::MbedTLS INTERFACE IMPORTED GLOBAL)
    set_property(TARGET MbedTLS::MbedTLS PROPERTY
        INTERFACE_LINK_LIBRARIES
        "MbedTLS::mbedtls;MbedTLS::mbedx509;MbedTLS::mbedcrypto")
endif()

# Exact git commit rather than a floating tag. These four recursive submodules
# are libdatachannel's datachannel/WSS build inputs; media is disabled, so
# libsrtp is intentionally absent from both fetch and binary.
set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
set(NO_MEDIA ON CACHE BOOL "" FORCE)
set(NO_WEBSOCKET OFF CACHE BOOL "" FORCE)
set(NO_EXAMPLES ON CACHE BOOL "" FORCE)
set(NO_TESTS ON CACHE BOOL "" FORCE)
set(USE_MBEDTLS ON CACHE BOOL "" FORCE)
set(USE_GNUTLS OFF CACHE BOOL "" FORCE)
set(USE_NICE OFF CACHE BOOL "" FORCE)
set(PREFER_SYSTEM_LIB OFF CACHE BOOL "" FORCE)
set(WARNINGS_AS_ERRORS OFF CACHE BOOL "" FORCE)
FetchContent_Declare(mdkr_libdatachannel
    GIT_REPOSITORY https://github.com/paullouisageneau/libdatachannel.git
    GIT_TAG "v${MDKR_LIBDATACHANNEL_VERSION}"
    GIT_SHALLOW TRUE
    GIT_SUBMODULES deps/plog deps/usrsctp deps/libjuice deps/json
    GIT_SUBMODULES_RECURSE TRUE
    PATCH_COMMAND "${CMAKE_COMMAND}"
      "-DSOURCE_DIR=<SOURCE_DIR>"
      "-DPATCH_FILE=${CMAKE_SOURCE_DIR}/cmake/patches/libdatachannel-windows-mbedtls-verify.patch"
      -P "${CMAKE_SOURCE_DIR}/cmake/apply_libdatachannel_patch.cmake")
FetchContent_MakeAvailable(mdkr_libdatachannel)

# The DTLS read-length fix is load-bearing on every platform: without it the
# Mbed TLS server side reports whole-buffer datagrams and no phone's first
# DTLS flight can ever complete the handshake. Upstream fixed it in v0.24.4
# (our former vendored patch, retired at the v0.24.5 bump), so this check now
# pins the upstream fix: an upstream regression, or a FETCHCONTENT_SOURCE_DIR
# override pointing at an older tree, must fail configuration, not pairing.
file(READ "${mdkr_libdatachannel_SOURCE_DIR}/src/impl/dtlstransport.cpp"
    MDKR_LIBDATACHANNEL_DTLS_SOURCE)
if(NOT MDKR_LIBDATACHANNEL_DTLS_SOURCE MATCHES "return int\\(bufMin\\)")
    message(FATAL_ERROR
        "libdatachannel Mbed TLS DTLS read-length patch was not applied")
endif()
unset(MDKR_LIBDATACHANNEL_DTLS_SOURCE)

if(WIN32)
    file(READ "${mdkr_libdatachannel_SOURCE_DIR}/src/impl/websocket.cpp"
        MDKR_LIBDATACHANNEL_WEBSOCKET_SOURCE)
    if(NOT MDKR_LIBDATACHANNEL_WEBSOCKET_SOURCE MATCHES
       "defined\\(_WIN32\\) && !USE_MBEDTLS")
        message(FATAL_ERROR
            "libdatachannel Windows Mbed TLS verification patch was not applied")
    endif()
endif()

# The native Phone Party gone-room classifier (I4,
# platform/party/libdatachannel_party_transport.cpp socketError) keys on the
# exact onError strings this library emits: "WebSocket connection failed" is
# the ONLY string a service-refused upgrade (the room DO's 404 for a
# deleted/expired room, the Worker's 401) can produce, and the distinct
# network-level strings are what keep genuinely transient failures on the
# bounded reconnect ladder instead. A dependency bump that rewords any of
# them would silently revert gone-room detection to always-retry with no
# failing test, so pin the literals at configure time, same as the patch
# checks above.
file(READ "${mdkr_libdatachannel_SOURCE_DIR}/src/impl/websocket.cpp"
    MDKR_LIBDATACHANNEL_ERROR_STRINGS_SOURCE)
foreach(MDKR_PARTY_CLASSIFIER_LITERAL
        "\"WebSocket connection failed\""
        "\"TCP connection failed\""
        "\"TLS connection failed\""
        "\"Connection timed out\"")
    string(FIND "${MDKR_LIBDATACHANNEL_ERROR_STRINGS_SOURCE}"
        "${MDKR_PARTY_CLASSIFIER_LITERAL}" MDKR_PARTY_CLASSIFIER_LITERAL_AT)
    if(MDKR_PARTY_CLASSIFIER_LITERAL_AT EQUAL -1)
        message(FATAL_ERROR
            "libdatachannel websocket.cpp no longer contains the literal "
            "${MDKR_PARTY_CLASSIFIER_LITERAL} that the Phone Party gone-room "
            "classifier (libdatachannel_party_transport.cpp socketError, I4) "
            "keys on. Re-verify the library's onError strings and update the "
            "classifier and this pin together.")
    endif()
endforeach()
unset(MDKR_LIBDATACHANNEL_ERROR_STRINGS_SOURCE)
unset(MDKR_PARTY_CLASSIFIER_LITERAL_AT)

# The shallow tag keeps transitive clone size bounded. Verify its immutable
# object id immediately, so a retagged upstream release fails configuration.
execute_process(
    COMMAND git rev-parse HEAD
    WORKING_DIRECTORY "${mdkr_libdatachannel_SOURCE_DIR}"
    OUTPUT_VARIABLE MDKR_LIBDATACHANNEL_ACTUAL_COMMIT
    OUTPUT_STRIP_TRAILING_WHITESPACE
    COMMAND_ERROR_IS_FATAL ANY)
if(NOT MDKR_LIBDATACHANNEL_ACTUAL_COMMIT STREQUAL MDKR_LIBDATACHANNEL_COMMIT)
    message(FATAL_ERROR
        "libdatachannel v${MDKR_LIBDATACHANNEL_VERSION} resolved to "
        "${MDKR_LIBDATACHANNEL_ACTUAL_COMMIT}, expected "
        "${MDKR_LIBDATACHANNEL_COMMIT}")
endif()

if(NOT TARGET LibDataChannel::LibDataChannel)
    message(FATAL_ERROR "Pinned libdatachannel did not export its reviewed target")
endif()

set(MDKR_LIBDATACHANNEL_JSON_INCLUDE
    "${mdkr_libdatachannel_SOURCE_DIR}/deps/json/single_include")

# Mbed TLS deliberately has no platform-specific implicit trust store. Embed a
# pinned Mozilla server-auth root extract so packaged apps retain hostname and
# chain verification without a Homebrew/OpenSSL runtime dependency.
set(MDKR_MOZILLA_CA_FILE
    "${CMAKE_BINARY_DIR}/_deps/cacert-${MDKR_MOZILLA_CA_DATE}.pem")
set(MDKR_CA_DOWNLOAD_REQUIRED TRUE)
if(EXISTS "${MDKR_MOZILLA_CA_FILE}")
    file(SHA256 "${MDKR_MOZILLA_CA_FILE}" MDKR_CA_CACHED_SHA256)
    if(MDKR_CA_CACHED_SHA256 STREQUAL MDKR_MOZILLA_CA_SHA256)
        set(MDKR_CA_DOWNLOAD_REQUIRED FALSE)
    endif()
endif()
if(MDKR_CA_DOWNLOAD_REQUIRED)
    file(DOWNLOAD
        "https://curl.se/ca/cacert-${MDKR_MOZILLA_CA_DATE}.pem"
        "${MDKR_MOZILLA_CA_FILE}"
        EXPECTED_HASH "SHA256=${MDKR_MOZILLA_CA_SHA256}"
        TLS_VERIFY ON
        STATUS MDKR_CA_DOWNLOAD_STATUS)
    list(GET MDKR_CA_DOWNLOAD_STATUS 0 MDKR_CA_DOWNLOAD_CODE)
    if(NOT MDKR_CA_DOWNLOAD_CODE EQUAL 0)
        list(GET MDKR_CA_DOWNLOAD_STATUS 1 MDKR_CA_DOWNLOAD_MESSAGE)
        message(FATAL_ERROR "Could not fetch pinned Mozilla CA bundle: ${MDKR_CA_DOWNLOAD_MESSAGE}")
    endif()
endif()
file(READ "${MDKR_MOZILLA_CA_FILE}" MDKR_CA_HEX HEX)
string(REGEX REPLACE "(..)" "0x\\1," MDKR_CA_BYTES "${MDKR_CA_HEX}")
set(MDKR_PARTY_GENERATED_INCLUDE "${CMAKE_BINARY_DIR}/generated/party")
file(MAKE_DIRECTORY "${MDKR_PARTY_GENERATED_INCLUDE}")
set(MDKR_CA_HEADER "${MDKR_PARTY_GENERATED_INCLUDE}/mozilla_ca_bundle.h")
set(MDKR_CA_HEADER_CONTENT
    "#ifndef MDKR_MOZILLA_CA_BUNDLE_H\n#define MDKR_MOZILLA_CA_BUNDLE_H\nstatic const unsigned char kMdkrMozillaCaBundle[] = {${MDKR_CA_BYTES}0x00};\nstatic const unsigned long kMdkrMozillaCaBundleLength = sizeof(kMdkrMozillaCaBundle) - 1UL;\n#endif\n")
set(MDKR_CA_HEADER_CURRENT "")
if(EXISTS "${MDKR_CA_HEADER}")
    file(READ "${MDKR_CA_HEADER}" MDKR_CA_HEADER_CURRENT)
endif()
if(NOT MDKR_CA_HEADER_CURRENT STREQUAL MDKR_CA_HEADER_CONTENT)
    file(WRITE "${MDKR_CA_HEADER}" "${MDKR_CA_HEADER_CONTENT}")
endif()
